version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/finance_app
      - DB_USERNAME=postgres
      - DB_PASSWORD=19283746511
    networks:
      - mynetwork

  frontend:
    build: ./frontend/.
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=19283746511
      - POSTGRES_DB=finance_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

